Student.create(first_name: "James", last_name: "Park")
Student.create(first_name: "Ducky", last_name: "Ko")
Student.create(first_name: "Kevin", last_name: "Mark")
Student.create(first_name: "Rasheed", last_name: "White")
Student.create(first_name: "Muhamed", last_name: "Singh")
